excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://usereugene.github.io
title: Awesome
email: aicuni2020@yahoo.com
author: usereugene
description: My awesome new site
paginate: 3
google_analytics: 